sudo: required

language: node_js

services:
  - docker

install: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

script: docker-compose exec nextjs /bin/sh -c "npm run lint"

before_deploy:
  - docker-compose exec nextjs /bin/sh -c "npm run export"

deploy:
  skip_cleanup: true
  provider: script
  script: docker-compose exec nextjs /bin/sh -c "$TRAVIS_BUILD_DIR/deploy.sh"
  on:
    branch: master

branches:
  only:
    - master

env:
  global:
    NOKOGIRI_USE_SYSTEM_LIBRARIES: true # speeds up installation of html-proofer
    ENCRYPTION_LABEL: aef673239dae
    COMMIT_AUTHOR_NAME: Travis
    COMMIT_AUTHOR_EMAIL: bot@schoenwald.media
