language: node_js
node_js:
  - "8.4.0"

services:
  - docker

after_install:
  - docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

script: npm run lint

deploy:
  skip_cleanup: true
  provider: script
  script: bash $TRAVIS_BUILD_DIR/scripts/deploy.sh
  on:
    branch: master

branches:
  only:
    - master

env:
  global:
    ENCRYPTION_LABEL: aef673239dae
    COMMIT_AUTHOR_NAME: Travis
    COMMIT_AUTHOR_EMAIL: bot@schoenwald.media

after_success:
  - if [[ $TRAVIS_PULL_REQUEST -ne "false" ]] && [[ $TRAVIS_BRANCH == 'develop' ]]; then node node_modules/lighthouse-ci/runlighthouse.js --score=80 http://timeline.schoenwald.media ; fi
