language: node

script: npm run lint

deploy:
  skip_cleanup: true
  provider: script
  script: bash $TRAVIS_BUILD_DIR/deploy.sh
  on:
    branch: master

branches:
  only:
    - master
env:
  global:
    NOKOGIRI_USE_SYSTEM_LIBRARIES: true # speeds up installation of html-proofer
    ENCRYPTION_LABEL: "aef673239dae"
    COMMIT_AUTHOR_EMAIL: "bot@schoenwald.media"
