language: node_js
node_js:
  - "8.4.0"

services:
  - docker

before_install:
  - sudo groupadd --gid 1000 dockerbuild && sudo usermod -a -G 1000 $USER && sudo chown -R :dockerbuild .
  - docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

script: npm run lint

before_deploy:
  - npm run export

deploy:
  skip_cleanup: true
  provider: script
  script: bash $TRAVIS_BUILD_DIR/deploy.sh
  on:
    branch: master

branches:
  only:
    - master

env:
  global:
    NOKOGIRI_USE_SYSTEM_LIBRARIES: true # speeds up installation of html-proofer
    ENCRYPTION_LABEL: aef673239dae
    COMMIT_AUTHOR_NAME: Travis
    COMMIT_AUTHOR_EMAIL: bot@schoenwald.media
