service: api-timeline # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs10.x

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: timeline.api.schoen.world
    certificateName: '*.api.schoen.world'
    basePath: ${self:provider.stage}
    stage: ${self:provider.stage}
    createRoute53Record: true

  # you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  updateTimelineData:
    handler: handler.updateTimelineData
    events:
       - http:
          path: updateTimelineData
          method: get

  getTimelineData:
    handler: handler.getTimelineData
    events:
       - http:
          path: getTimelineData
          method: get
