### .github/workflows/dependabot_pr.yml
### This workflow doesn't have access to secrets and has a read-only token
name: PR
on:
  pull_request:
    branches:
      - main

jobs:
  check-dependabot:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR created"
