name: schoen-world

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: test types
        run: pnpm test:types

      - name: test e2e
        run: pnpm test:e2e

      - name: test int
        run: pnpm test:int

      - name: lint ts
        run: pnpm lint:ts

      - name: lint md
        run: pnpm lint:md

      - name: build
        run: pnpm build
